//HintName: DiceRoll.g.cs
// <auto-generated/>
// Disable CS1591 - Missing XML comment on public member
#pragma warning disable 1591
// Disable CS8604 - Possible null reference argument for parameter.
#pragma warning disable 8604
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("PrimitiveJsonConverter.Generator", "1.0.4+649e6fb2549fc496aeddb622b963e3d01ee0cc2a")]
[global::System.Text.Json.Serialization.JsonConverter(typeof(DiceRollPrimitiveJsonConverter))]
public partial record DiceRoll
{
}
// Disable CS1591 - Missing XML comment on public member
#pragma warning restore 1591
// Disable CS8604 - Possible null reference argument for parameter.
#pragma warning restore 8604
