//HintName: PrimitiveJsonConverterLoader2.g.cs
﻿// <auto-generated />
﻿#nullable enable
﻿using System.Text.Json;
namespace PrimitiveJsonConverter.Generator
{
	internal static partial class PrimitiveJsonConverterLoader
	{
		public static partial void Load()
		{
			DiceRollPrimitiveJsonConverter.Load();
		}
	}
}
﻿#nullable disable
